Gradle improvements v2
Lembas-Modding-Team/pvp-mode pull request #330
Opened 2019-01-22 17:01 UTC by Mahtaran

Organised the `.gitignore` file and added directories which should be ignored.
Updated to Gradle 4.4 from 2.0. Changed several things in accordance with this.
Moved all configurable settings from the `build.gradle` file to `build.properties`.
Increased the maximum amount of RAM Gradle can use while compiling for faster builds.
Added all required libs (and some not required at this moment but they might be in the future (SuffixForge)) to build the mod.
Added an automated system which replaces placeholders like the modid, version and Minecraft version.

After it is reviewed, it should be tested if the newly compiled JAR doesn't break everything.

2019-01-24 12:07 UTC, CraftedMods requested changes
That is the first part of my review.

2019-01-24 12:10 UTC, Mahtaran commented on build.gradle
> +    shadow "io.github.lukehutch:fast-classpath-scanner:2.21"
What do you mean? I’m pretty sure it was in the compiled JAR.

2019-01-24 12:11 UTC, CraftedMods commented on build.gradle
> +    shadow "io.github.lukehutch:fast-classpath-scanner:2.21"
I did build it several times, and it wasn't there.

2019-01-24 12:40 UTC, Mahtaran commented on build.gradle
> +    shadow "io.github.lukehutch:fast-classpath-scanner:2.21"
using what task did you build?

2019-01-24 12:41 UTC, CraftedMods commented on build.gradle
> +    shadow "io.github.lukehutch:fast-classpath-scanner:2.21"
`build`

2019-01-24 16:49 UTC, Mahtaran commented on build.gradle
> +    shadow "io.github.lukehutch:fast-classpath-scanner:2.21"
Problem confirmed. Moving to fix it now.

2019-01-24 17:40 UTC, Mahtaran commented on build.gradle
> +    shadow "io.github.lukehutch:fast-classpath-scanner:2.21"
@CraftedMods Should be resolved. Feel free to try again.

2019-01-24 17:41 UTC, CraftedMods commented on build.gradle
> +    shadow "io.github.lukehutch:fast-classpath-scanner:2.21"
I'll try it tomorrow.

2019-01-26 13:46 UTC, CraftedMods commented on build.gradle
> +        provided "com.enderio.core:endercore:0.2.0-beta.39"
Why don't we just use the `compile` configuration?

2019-01-26 13:47 UTC, CraftedMods commented on build.gradle
> +    shadow
Innecessary line. The shadow plugin registers the configuration by it's own.

2019-01-26 13:48 UTC, CraftedMods commented on build.gradle
> +
Please replace that empty line with a comment.
```suggestion
// Dependencies that will be included ("shadowed") into the built JAR
```

2019-01-26 13:53 UTC, CraftedMods commented on build.gradle
>  jar {
The `jar` task can be completely removed, because the `shadowJar` task extends it.
You can replace the current `jar` and `shadowJar` tasks with that code: ```
shadowJar {
	classifier= ""
	
    manifest {
        attributes "FMLCorePlugin": "pvpmode.internal.common.core.PvPModeCore"
        attributes "FMLCorePluginContainsFMLMod": "true"
    }
    
    from("./") {
        include "*.md" // Include the markdown files
    }
    
    exclude "META-INF/**"
    exclude "META-INF/*"
    
    configurations = [project.configurations.shadow]
}
```

2019-01-26 13:57 UTC, CraftedMods commented on build.gradle
> +    provided fileTree(dir: dependenciesConfig.libraries + (dependenciesConfig.obfuscated ? "" : "Deobf"), include: ["*.jar"])
What does that do?

2019-01-26 17:06 UTC, Mahtaran commented on build.gradle
> +    provided fileTree(dir: dependenciesConfig.libraries + (dependenciesConfig.obfuscated ? "" : "Deobf"), include: ["*.jar"])
This adds all files in the `libs` or `libsDeobf` to the compile class path.

2019-01-26 17:10 UTC, Mahtaran commented on build.gradle
>  jar {
Why do you exclude the META-INF files? The `shadow` task automatically removes these from shadowed dependencies.

2019-01-26 17:12 UTC, Mahtaran commented on build.gradle
> +task cleanBuild(dependsOn: ["buildInformation", "startBuild", "clean", "build", "shadowJar", "finishBuild"]) {
Gradle recommends that you don’t change the logic of built-in tasks as it may result in hard to find bugs.
I added the `clean` task

2019-01-26 17:16 UTC, Mahtaran commented
The rest will be addressed tomorrow when I have access to a PC again.

2019-01-26 21:19 UTC, CraftedMods commented on build.gradle
>  jar {
I thought that too, but then I rechecked the documentation - it only removes those:
`META-INF/INDEX.LIST`
`META-INF/*.SF`
`META-INF/*.DSA`
`META-INF/*.RSA`

2019-01-27 10:47 UTC, Mahtaran commented on build.gradle
> +        provided "com.enderio.core:endercore:0.2.0-beta.39"
Because I thought using `provided` as keyword would make more sense. I have replaced it with `compile` in my latest commit.

2019-01-27 11:18 UTC, CraftedMods commented on build.gradle
> +	relocate "io.github.lukehutch.fastclasspathscanner", "pvpmode.fastclasspathscanner"
For "credit" and code separation reasons, I think it would be better to name it `pvpmode.shadow.io.github.lukehutch.fastclasspathscanner`.

2019-01-27 15:39 UTC, CraftedMods commented on build.gradle
> +task cleanBuild(dependsOn: ["buildInformation", "startBuild", "clean", "build", "shadowJar", "finishBuild"]) {
I'm not completely sure, but isn't the `cleanBuild` task slower than the `build` task, because really everything will be rebuilt? If that's the case, I would suggest you to move the `clean` part to the `publish` task. If one wants a `clean` environment, one can always use `gradle build clean`.

2019-01-27 15:59 UTC, CraftedMods commented on build.gradle
> +def startBuildMessage = "Starting build...\n\nName: ${project.name}\nVersion: ${project.version}"
We could replace the whole build message code with that:
```
gradle.afterProject {
    println "\n### Building ${project.name} (${project.version}) ###\n"
}
```
The message could even be colored, if we would use internal classes.

2019-01-27 16:11 UTC, Mahtaran commented on build.gradle
> +task cleanBuild(dependsOn: ["buildInformation", "startBuild", "clean", "build", "shadowJar", "finishBuild"]) {
I’ll look into it.

2019-01-27 16:15 UTC, Mahtaran commented on build.gradle
> +def startBuildMessage = "Starting build...\n\nName: ${project.name}\nVersion: ${project.version}"
I primarily added this since we use a similar message on another mod I’m working on, but there it’s mostly because the mod is aimed to be built by users without a lot of technical knowledge. I guess that we could remove the last message and make the first shorter.

2019-01-27 16:16 UTC, Mahtaran commented on build.gradle
> +def finishBuildMessage = "Successfully finished building ${project.name} version ${project.version}\n\nYour build is located in:\nbuild/libs"
Again, this is primarily something we did on my other project to help users who do not know where Gradle stores the built files.

2019-01-27 16:19 UTC, Mahtaran commented on build.gradle
> +	if (dependenciesConfig.obfuscated) {
I guess that’d be possible.

2019-02-08 19:44 UTC, Mahtaran commented on build.gradle
> +task cleanBuild(dependsOn: ["buildInformation", "startBuild", "clean", "build", "shadowJar", "finishBuild"]) {
After doing 5 consecutive runs of both tasks, I got the following results:

> ```gradlew cleanBuild```
> 9s, 7s, 7s, 7s, 7s
> 16 actionable tasks: 14 executed, 2 up-to-date
> 
> ```gradlew build```
> 2s, 2s, 2s, 1s, 2s
> 12 actionable tasks: 4 executed, 8 up-to-date

It seems like you're right. I'll merge this task with the `publish` task.

2019-02-14 09:40 UTC, CraftedMods commented on build.gradle
> +tasks.wrapper.dependsOn buildInformation
When is that executed?

2019-02-14 11:32 UTC, Mahtaran commented
Wrapper is the first task executed in the build, haven’t tested if it’s
executed in other tasks, but that doesn’t really matter in my opinion, as
all executed tasks have to do with the project.

On Thu, 14 Feb 2019 at 10:40, CraftedMods <notifications@github.com> wrote:

> *@CraftedMods* commented on this pull request.
> ------------------------------
>
> In build.gradle
> <https://github.com/Lembas-Modding-Team/pvp-mode/pull/330#discussion_r256755221>
> :
>
> > +		for (String line : lines)
> +			maxLength = Math.max(line.length(), maxLength)
> +		for (def i = 0; i < maxLength; i++) {
> +			border += i % 2 == 0 ? "=" : "-"
> +		}
> +		println """
> +${border}
> +
> +${message}
> +
> +${border}
> +"""
> +	}
> +}
> +
> +tasks.wrapper.dependsOn buildInformation
>
> When is that executed?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Lembas-Modding-Team/pvp-mode/pull/330#pullrequestreview-203646024>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVrKm4QpezzSOb-qWU7tnintIY5EinjCks5vNS8XgaJpZM4aNG4a>
> .
>

2019-02-14 15:25 UTC, CraftedMods commented
The task isn't executed. I tried using both `build` and `clean build`.

2019-02-14 15:27 UTC, Mahtaran commented
> 
> 
> The task isn't executed. I tried using both `build` and `clean build`.

You are using the `gradlew` command instead of the `gradle` command right?

2019-02-14 15:47 UTC, CraftedMods commented
Yes.

2019-02-14 15:50 UTC, CraftedMods commented
Also, I noticed, that I cannot use the Hot Code replacement eclipse has, because I've to start the program via gradle now. That's bad and makes development hard, for some things, because then I've to restart the program with every change. It's probably still possible somehow, but not as easy as it was.

2019-02-14 15:56 UTC, CraftedMods commented
If you don't know a better solution, I would recommend to remove these lines:
```
replaceIn "src/main/java/pvpmode/PvPMode.java"
	replace "@version@", config.version
	replace "@modid@", config.modid
	replace "@mcversion@", project.minecraft.version
	replace "@name@", config.name
```
This is not ideal, but honestly I rather want to change  the mod version at one place more before an update, than not having the hotswapping. Starting the program without gradle is also more convenient and more easy, for me in eclipse, because the Forge workspace layout creates some problems with the eclipse gradle plugin.

2019-02-14 19:40 UTC, Mahtaran commented
I guess we could work around 

> 
> 
> Yes. `gradle` doesn't work, using the Forge Dev Environment.

Ah, problem confirmed. Weird, it worked before. Resolved, replaced `tasks.wrapper` with `tasks.compileApiJava`. Going to be in the next commit, after I look into the hot swapping.

2024-02-28 21:15 UTC, closed without merging